interface Currency {
  symbol: string;
  name: string;
}

export const currencies: Currency[] = [
  { symbol: 'BTC', name: 'Bitcoin' },
  { symbol: 'ETH', name: 'Ethereum' },
  { symbol: 'NEO', name: 'Neo' },
  { symbol: 'MTL', name: 'Metal' },
  { symbol: 'XRP', name: 'XRP' },
  { symbol: 'ETC', name: 'Ethereum Classic' },
  { symbol: 'SNT', name: 'Status Network Token' },
  { symbol: 'WAVES', name: 'Waves' },
  { symbol: 'XEM', name: 'NEM' },
  { symbol: 'QTUM', name: 'Qtum' },
  { symbol: 'LSK', name: 'Lisk' },
  { symbol: 'STEEM', name: 'Steem' },
  { symbol: 'XLM', name: 'Stellar' },
  { symbol: 'ARDR', name: 'Ardor' },
  { symbol: 'ARK', name: 'Ark' },
  { symbol: 'STORJ', name: 'Storj' },
  { symbol: 'GRS', name: 'Groestlcoin' },
  { symbol: 'ADA', name: 'Cardano' },
  { symbol: 'SBD', name: 'Steem Dollars' },
  { symbol: 'POWR', name: 'Power Ledger' },
  { symbol: 'BTG', name: 'Bitcoin Gold' },
  { symbol: 'ICX', name: 'ICON' },
  { symbol: 'EOS', name: 'EOS' },
  { symbol: 'TRX', name: 'TRON' },
  { symbol: 'SC', name: 'Siacoin' },
  { symbol: 'ONT', name: 'Ontology' },
  { symbol: 'ZIL', name: 'Zilliqa' },
  { symbol: 'POLYX', name: 'Polymesh' },
  { symbol: 'ZRX', name: '0x' },
  { symbol: 'LOOM', name: 'Loom Network' },
  { symbol: 'BCH', name: 'Bitcoin Cash' },
  { symbol: 'BAT', name: 'Basic Attention Token' },
  { symbol: 'IOST', name: 'IOST' },
  { symbol: 'CVC', name: 'Civic' },
  { symbol: 'IQ', name: 'Everipedia' },
  { symbol: 'IOTA', name: 'IOTA' },
  { symbol: 'HIFI', name: 'HiFi Finance' },
  { symbol: 'ONG', name: 'Ontology Gas' },
  { symbol: 'GAS', name: 'Gas' },
  { symbol: 'BOUNTY', name: 'Chainbounty' },
  { symbol: 'ELF', name: 'aelf' },
  { symbol: 'KNC', name: 'Kyber Network' },
  { symbol: 'BSV', name: 'Bitcoin SV' },
  { symbol: 'THETA', name: 'Theta Network' },
  { symbol: 'QKC', name: 'QuarkChain' },
  { symbol: 'BTT', name: 'BitTorrent' },
  { symbol: 'MOC', name: 'Moss Coin' },
  { symbol: 'TFUEL', name: 'Theta Fuel' },
  { symbol: 'MANA', name: 'Decentraland' },
  { symbol: 'ANKR', name: 'Ankr' },
  { symbol: 'AERGO', name: 'Aergo' },
  { symbol: 'ATOM', name: 'Cosmos' },
  { symbol: 'TT', name: 'ThunderCore' },
  { symbol: 'GAME2', name: 'GameBuild' },
  { symbol: 'MBL', name: 'MovieBloc' },
  { symbol: 'WAXP', name: 'WAX' },
  { symbol: 'HBAR', name: 'Hedera' },
  { symbol: 'MED', name: 'MediBloc' },
  { symbol: 'MLK', name: 'Milk Alliance' },
  { symbol: 'STPT', name: 'Standard Tokenization Protocol' },
  { symbol: 'ORBS', name: 'Orbs' },
  { symbol: 'VET', name: 'VeChain' },
  { symbol: 'CHZ', name: 'Chiliz' },
  { symbol: 'STMX', name: 'StormX' },
  { symbol: 'DKA', name: 'dKargo' },
  { symbol: 'HIVE', name: 'Hive' },
  { symbol: 'KAVA', name: 'Kava' },
  { symbol: 'AHT', name: 'AhaToken' },
  { symbol: 'LINK', name: 'Chainlink' },
  { symbol: 'XTZ', name: 'Tezos' },
  { symbol: 'BORA', name: 'BORA' },
  { symbol: 'JST', name: 'JUST' },
  { symbol: 'CRO', name: 'Cronos' },
  { symbol: 'TOKAMAK', name: 'Tokamak Network' },
  { symbol: 'SXP', name: 'Swipe' },
  { symbol: 'HUNT', name: 'Hunt' },
  { symbol: 'DOT', name: 'Polkadot' },
  { symbol: 'MVL', name: 'MVL' },
  { symbol: 'STRAX', name: 'Stratis' },
  { symbol: 'AQT', name: 'Alpha Quark Token' },
  { symbol: 'GLM', name: 'Golem' },
  { symbol: 'META', name: 'Metadium' },
  { symbol: 'FCT2', name: 'FirmaChain' },
  { symbol: 'CBK', name: 'Cobak Token' },
  { symbol: 'SAND', name: 'The Sandbox' },
  { symbol: 'HPO', name: 'Hippocrat' },
  { symbol: 'DOGE', name: 'Dogecoin' },
  { symbol: 'STRIKE', name: 'Strike' },
  { symbol: 'PUNDIX', name: 'Pundi X' },
  { symbol: 'FLOW', name: 'Flow' },
  { symbol: 'AXS', name: 'Axie Infinity' },
  { symbol: 'STX', name: 'Stacks' },
  { symbol: 'XEC', name: 'eCash' },
  { symbol: 'SOL', name: 'Solana' },
  { symbol: 'POL', name: 'Polygon Ecosystem Token' },
  { symbol: 'AAVE', name: 'Aave' },
  { symbol: '1INCH', name: '1inch' },
  { symbol: 'ALGO', name: 'Algorand' },
  { symbol: 'NEAR', name: 'NEAR Protocol' },
  { symbol: 'AVAX', name: 'Avalanche' },
];
